export const SOLUTION_METHODS = {
  SINGLE_CANDIDATE: "唯一余数法",
  HIDDEN_SINGLE_ROW: "隐性单数法（行）",
  HIDDEN_SINGLE_COLUMN: "隐性单数法（列）",
  HIDDEN_SINGLE_BOX: "隐性单数法（宫）",
  BLOCK_ELIMINATION_ROW: "区块摒除法(行)",
  BLOCK_ELIMINATION_COLUMN: "区块摒除法(列)",
  BLOCK_ELIMINATION_BOX_ROW: "区块摒除法(宫-行)",
  BLOCK_ELIMINATION_BOX_COLUMN: "区块摒除法(宫-列)",
  NAKED_PAIR: "显性数对法",
  HIDDEN_PAIR: "隐形数对法",
  X_WING: "X-Wing",
  XY_WING: "XY-Wing",
  XYZ_WING: "XYZ-Wing",
  // X_CHAIN: "X-Chain",
};
